greenexit

diff --git a/bin/watchrun b/bin/watchrun
--- a/bin/watchrun
+++ b/bin/watchrun
@@ -30,10 +30,13 @@ OPTIONS
 
         --redexit
         --no-redexit
-            This option, enabled by default, appends a call to the `redexit` command
-            to the 
-            watchman-make is invoked. A failure of the initial run does not
-            prevent subsequent runs.
+            This option, enabled by default, appends message in red text
+            if the command failed.
+
+        --greenexit
+        --no-greenexit
+            This option, enabled by default, appends message in green text
+            if the command succeeded.
 
 EXAMPLES
         watchrun 'scripts/*' '*.yaml' --no-initial-run -- pytest -k 'pytest pattern'
@@ -48,6 +51,7 @@ EOM
 SEEN_DOUBLE_DASH=false
 INITIAL_RUN=true
 RED_EXIT=true
+GREEN_EXIT=true
 PRE_DASH_ARGS=()
 while (( $# > 0 )) && [[ $SEEN_DOUBLE_DASH == false ]]; do
     case "$1" in
@@ -56,6 +60,8 @@ while (( $# > 0 )) && [[ $SEEN_DOUBLE_DASH == false ]]; do
         --no-initial-run) INITIAL_RUN=false ;;
         --redexit) RED_EXIT=true ;;
         --no-redexit) RED_EXIT=false ;;
+        --greenexit) GREEN_EXIT=true ;;
+        --no-greenexit) GREEN_EXIT=false ;;
         *) PRE_DASH_ARGS+=("$1") ;;
     esac
     shift
@@ -75,14 +81,23 @@ while (( $# > 0 )); do
     shift
 done
 
+COMMAND_AND_ARGS="$POST_DASH_ARGS"
+
 # invoke watchman-make
 echo "PATTERNS:		${PRE_DASH_ARGS[@]}"
-echo "COMMAND_AND_ARGS:	$POST_DASH_ARGS"
+echo "COMMAND_AND_ARGS:	$COMMAND_AND_ARGS"
 
+NC='\033[0m' # No Color
+GREEN='\033[32m'
+RED='\033[0;31m'
+# RED_BG='\033[41m'
+# GREEN_BG='\033[42m'
+if [[ $GREEN_EXIT == true ]]; then
+    GREEN_EXIT_STR=" && echo -e '${GREEN}'\"command $COMMAND_AND_ARGS succeeded \"'${NC}'"
+    POST_DASH_ARGS+="$GREEN_EXIT_STR"
+fi
 if [[ $RED_EXIT == true ]]; then
-    RED='\033[0;31m'
-    NC='\033[0m' # No Color
-    RED_EXIT_STR=" || { ret=\$?; echo '${RED}'\"command \"$POST_DASH_ARGS\" failed with exit code \$ret\"'${NC}'; }"
+    RED_EXIT_STR=" || { ret=\$?; echo -e '${RED}'\"command $COMMAND_AND_ARGS failed with exit code \$ret\"'${NC}'; }"
     POST_DASH_ARGS+="$RED_EXIT_STR"
 fi
 
