fix bug

diff --git a/bin/watchrun b/bin/watchrun
--- a/bin/watchrun
+++ b/bin/watchrun
@@ -82,10 +82,7 @@ echo "COMMAND_AND_ARGS:	$POST_DASH_ARGS"
 if [[ $RED_EXIT == true ]]; then
     RED='\033[0;31m'
     NC='\033[0m' # No Color
-    RED_EXIT_STR=" || ret=$?;"
-    RED_EXIT_STR+=" echo -e '${RED}command \"$POST_DASH_ARGS\" failed with exit code'"
-    RED_EXIT_STR+=' $ret'
-    RED_EXIT_STR+="'${NC}'"
+    RED_EXIT_STR=" || { ret=\$?; echo '${RED}'\"command \"$POST_DASH_ARGS\" failed with exit code \$ret\"'${NC}'; }"
     POST_DASH_ARGS+="$RED_EXIT_STR"
 fi
 
